# Generated by Django 4.1.7 on 2023-03-27 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_merge_20230327_0320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupbook',
            options={'verbose_name': 'Group Pass', 'verbose_name_plural': 'Group Passes'},
        ),
    ]
